### ISSUE TITLE
Aify service not working after following readme

### ISSUE THREAD

**Issue by Michspirit99** [shellc/aify#1]
I have all dependencies installed, and i followed the readme exactly, but when trying to execute a YAML file  in the apps folder using
aify run ./apps in bash, i get 'command not found'. 

How exactly can we run the service? 

![image](https://github.com/shellc/aify/assets/11279621/74cfb67b-bbb1-49e5-aa78-1dd86da833b9)

**Comment by shellc** [comment]
Please tell me your current version: pip list | grep aify

A quick way to try to fix it is:

python -m aify run

The version of aify updates quickly, you can try: pip install aify --upgrade to the latest version

I will investigate the reason why aify cannot run directly.

**Comment by Michspirit99** [comment]
Thank you for your rapid response!!

Here is the current version:

![image](https://github.com/shellc/aify/assets/11279621/9ea5f9f4-3b0d-4263-9597-0fc2ebb618bc)

python -m aify run did work, however i got this in the console which i believe led to a blank startup screen:

![image](https://github.com/shellc/aify/assets/11279621/38b37f3d-f869-47b7-b12c-a5230f9f8e06)

**Comment by Michspirit99** [comment]
It seems to be looking for 2 files in /aify/ however, the only files that exist like that are in the js build folder. I don't think the file reference is correct, or this is a missing build step, imo.

![image](https://github.com/shellc/aify/assets/11279621/da5ecd0f-f6f8-46dd-a70d-d73e3ad458c0)

**Comment by shellc** [comment]
I created a Python virtual environment using conda to test this issue, and it seems to be working fine. Could you give me more information?



> 

It seems like you are working on Windows, and I haven't tested it on a Windows system. Sorry.

You should directly use "pip install aify" to install it. This way, the "aify" library and scripts will be placed in the site-packages directory of Python and will be found correctly.

If you execute the code directly cloned from GitHub, you will need some preparation work for the development environment.

The "js" directory contains the frontend code that has not been compiled. If you want to compile the frontend code, you can go into the "js" directory and execute "npm run build".

**Comment by Michspirit99** [comment]
No worries! I don't mind being the test subject for windows setups.

I'm using vs code with windows git bash installed. It shouldn't really be that different from a typical linux bash environment. 

So i installed via "pip install aify":
![image](https://github.com/shellc/aify/assets/11279621/f3274cef-6e2c-41ee-a9b3-6bf4fa2650fc)

And i compiled the build files here:

![image](https://github.com/shellc/aify/assets/11279621/bb1688cc-1609-470e-b236-434955413366)

I don't think i'm doing anything wrong at this point, and i've even run it in the python interpreter.

Hopefully you see something above, but if not i'll figure it out, and do a pull request.

**Comment by shellc** [comment]
Great job!

If you want to execute the code after cloning it from GitHub, please follow these steps:

cd aify/js
npm run build
cp ./build/aify.* ../webui/static/aify/
cd ..
export PYTHONPATH=.
./bin/aify examples

Now the aify module points to the aify in the current directory, and the executable file is ./bin/aify. The front-end page is in the webui directory. 

The completed packaging tool is build.sh, please comment out the last line that uploads to pipy.

**Comment by Michspirit99** [comment]
Will give it a shot!

**Comment by shellc** [comment]
I think the problem may occur because the PYTHONPATH points to the source code directory with higher priority, so even if pip install aify, the priority of the aify module in the site-packages directory is lower than that in the source code directory. This causes the execution phase to search for static file resources in the source code directory.

Feel free to start playing with the source code 😄. However, please forgive me for not having written any documentation for potential code contributors.

Please feel free to give me any feedback.

**Comment by Michspirit99** [comment]
Such a silly and simple mistake on my part. I had to manually add the python packages and scripts to PATH. 

Just an FYI for Windows users, installing a package via pip, npm, etc..does not mean that the system will add your packages to PATH, which is required for the system to recognize commands. 

This is working as intended now.
